### ISSUE TITLE
Typos and Additions

### ISSUE THREAD

**Issue by wolvespaw** [TumblrCommunity/coding-masterpost#11]
In ReadMe
*Standford --> Stanford
(Can't edit easily from mobile)

**Comment by wolvespaw** [comment]
In Resources/Masterpost1
---
+Udacity -- similar to Udemy, Coursera, and EdX
+O'Reilly Media Data Science archives
<http://www.oreilly.com/data/free/archive.html?imm_mid=0e7547&cmp=em-data-free-na-stny16_nem4_end_summer>
-------
Will add more later

**Comment by incomingstick** [comment]
I would recommend making this issue on your forked repo and then implementing the changes there. That way we can keep the upstream repository clean.

Please close when you see this.
